[PROXY]
# Just the host. Credentials should be inserted manually
# Deixar vazio em rede corporativa.
# Example: proxy.company.com:804
host = 

[PATHS]
# I used relative paths in order to funcion anywhere
base_dir = .
data_dir = data
vector_db_dir = vector_db
cache_dir = .cache/huggingface
CERTIFICATE_PATH = xxxxx

[MODELS]
embedding_model = BAAI/bge-m3
device = cuda
# In case of using GPU

[ENVIRONMENT]
# GPU Performance settings
pytorch_alloc_conf = expandable_segments:True
transformers_offline = 1

[TST]
APIM_BASE_URL = xxxxx
apikey_modelos_texto = xxxxx

[OPENAI]
OPENAI_API_KEY = xxxxx
OPENAI_API_VERSION = xxxxx
AZURE_OPENAI_BASE_URL = xxxxx
CHATGPT_MODEL = xxxxx
CERTIFICATE_PATH = xxxxx

[AWS]
# ID do modelo Claude no Bedrock
BEDROCK_CLAUDE_MODEL_ID = xxxxx
# [Opcional] Se precisar de configurações de região específicas
REGION_NAME = us-east-1
IAAWS_API_KEY=xxxxx