# .streamlit/config.toml
[server]
port = 3000             # A porta padrão do Streamlit (mantenha se não houver conflito)
headless = false         # Opcional: não abre o navegador automaticamente na sua máquina
enableCORS = false      # Permite conexões de diferentes origens (muitas vezes necessário em redes corporativas)
enableXsrfProtection = false # Desabilita proteção XSRF (pode ser necessário, mas com cuidado de segurança)
baseUrlPath = ""        # Se sua app não está em um subdiretório
fileWatcherType = "none"

# IMPORTANTE: Permite acesso de qualquer IP na rede
# ALTERNATIVAS:
# Para permitir apenas da sua máquina: address = "localhost" (padrão)
# Para permitir de qualquer IP na rede:
address = "0.0.0.0"


[theme]
# Cor primária do seu site (usada no botão primário, sliders, etc.)
primaryColor = "#0d6efd"  # Exemplo: um azul vibrante
# Cor de fundo principal do app
backgroundColor = "#ffffff"  # Exemplo: branco
# Cor de fundo da barra lateral e outros elementos secundários
secondaryBackgroundColor = "#f0f2f6"  # Exemplo: um cinza bem claro
# Cor principal do texto
textColor = "#262730"  # Exemplo: um cinza escuro
# Fonte (opcional, pode ser 'sans serif', 'serif', ou 'monospace')
# font = "sans serif"